# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

MopaBootstrapSandbox:
    resource: "@MopaBootstrapSandboxBundle/Controller"
    type:     annotation

_welcome:
    pattern:   /
    defaults:  { _controller: MopaBootstrapSandboxBundle:Examples:index }
    

MopaUpdateBundle:
    type:     rest
    resource: "@MopaRemoteUpdateBundle/Resources/config/routing.yml"
    
liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme