services:
    mopa_bootstrap.examplemenu_builder:
        class: %mopa_bootstrap.topbar.generic%
        arguments: ["Topbar Title", "title_route", @mopa_bootstrap.examplemenu, @mopa_bootstrap.exampledropdown]